In [3]:
import numpy as np
arr3 = np.array([1,2,3,4,6,5,7,8,9,10,11,12])
new_arr3 = arr3.reshape(6,1)
print(new_arr3)

[[1]
 [2]
 [3]
 [4]
 [6]
 [5]]


In [7]:
import numpy as nm
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).copy)

<built-in method copy of numpy.ndarray object at 0x000001F6B827E130>


NameError: name 'ar' is not defined

In [ ]:
length=0
    alternating_array = []
    for i in range(length):
        
        alternating_array.append((-1)**i * (i + 1))
    print(alternating_array)


n = 10


result = create_alternating_array(n)


print(result)


In [12]:
import numpy as np
arr = np.array([[1,2,3,],[1,2,3]])
for x in arr:
    for y in x:
        print(y)

1
2
3
1
2
3


In [25]:
import numpy as np


array1 = np.array([[1, 2], [3,4]])
array2 = np.array([[5, 6], [7,8]])

arr = np.concatenate((array1,array2) , axis = 1)
arr



array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [18]:

array1 = np.array([1, 2], [3,4])
array2 = np.array([5, 6],)


added_array = array1 + array2
print("Added Array:", added_array)

Added Array: [5 7 9]


In [27]:
import numpy as np


arr = np.array([5, 2, 9,8, 1, 5, 6])


sorted_arr = np.sort(arr)[::-1]

print(sorted_arr)


[9 8 6 5 5 2 1]


In [28]:
import numpy as np
array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
sorted_array = np.sort(array)
descending_array = np.flip(sorted_array)
print(descending_array)


[9 6 5 5 4 3 2 1 1]


In [34]:
import numpy as nm
arr9 = (['banana','Cherry','Apple'])
arr9 = np.sort(arr9)
arr9

array(['Apple', 'Cherry', 'banana'], dtype='<U6')

In [ ]:
arr8 = np.([41,43,42,44])
c = [True,True,False,True]

In [46]:
arr8 = np.array([1,2,3,4,5,6,7,8,9])

for i in arr8:
    if d == arr8[i]%2 == 0:
        d == True
    
    else:
        d = arr8[i]%2 != 0
        d == False

    print(i)




NameError: name 'd' is not defined

In [47]:
import numpy as np

arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

for i in arr8:
    if i % 2 == 0:
        d = True
        print(i)
    else:
        d = False


2
4
6
8
